version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../.dev/default.conf:/etc/nginx/conf.d/default.conf
      - ../.dev:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: client:dev
    build:
      context: ./client
    environment:
      LD_PRELOAD: /dns-cache.so
    volumes:
      - ../.dev:/var/www/html
      - ./dns_cache:/dns_cache
      - ../.dev/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
    networks:
      - app-network
  
  server:
    image: golang:1.18
    volumes:
      - ./dns_cache:/dns_cache
      - ./server:/server
    command: go run /server/main.go

networks:
  app-network:
    driver: bridge
