[package]
name = "xdp_udp_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redbpf = "2.3.0"
redbpf-probes = "2.3.0"
tokio = { version = "1.36.0", features = ["full"] }
bytes = "1.5.0"